import data from './exercises.json';

/**
 * One row of the bundled library. Generated by `npm run seed:build` from
 * free-exercise-db (D12) — see docs/exercise-weight-review.md for how
 * `weightApplicable` was decided.
 */
export type SeedExercise = {
  readonly id: string;
  readonly name: string;
  readonly primaryMuscle: string;
  readonly secondaryMuscles: readonly string[];
  readonly equipment: string | null;
  readonly exerciseType: string;
  readonly instructions: string | null;
  readonly weightApplicable: boolean;
};

export const seedExerciseData: readonly SeedExercise[] = data as SeedExercise[];
