/**
 * One row of the bundled library. Generated by `npm run seed:build` from
 * free-exercise-db (D12) — see docs/exercise-weight-review.md for how
 * `weightApplicable` was decided.
 */
export type SeedExercise = {
  readonly id: string;
  readonly name: string;
  readonly primaryMuscle: string;
  readonly secondaryMuscles: readonly string[];
  readonly equipment: string | null;
  readonly exerciseType: string;
  readonly instructions: string | null;
  readonly weightApplicable: boolean;
};

/**
 * The bundled library, loaded on demand.
 *
 * `require` inside a function, never a top-level `import`: Metro evaluates a
 * module the first time it is required, and a static import here would build
 * all 873 objects on every cold start — including the overwhelming majority of
 * launches, where the library is already in SQLite and this data is dead
 * weight. Behind `seedExercises`' count check it is read exactly once in the
 * app's lifetime.
 *
 * 776 KB, three quarters of it instruction text. What remains in the bundle is
 * Hermes bytecode, which is mapped rather than parsed, so the cost of keeping
 * it there is disk rather than startup time.
 */
export function loadSeedExercises(): readonly SeedExercise[] {
  return require('./exercises.json') as readonly SeedExercise[];
}
