// Generated by scripts/build-migrations.mjs. Do not edit.
export const name = '0000_unusual_the_spike';
export const version = 1;
export const statements = [
  `CREATE TABLE \`settings\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`unit\` text NOT NULL,
	\`week_start_day\` integer NOT NULL,
	\`default_increment\` real NOT NULL,
	\`updated_at\` integer NOT NULL
);`,
] as const;
