// Generated by scripts/build-migrations.mjs. Do not edit.
export const name = '0001_safe_darkstar';
export const version = 2;
export const statements = [
  `CREATE TABLE \`exercises\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`primary_muscle\` text NOT NULL,
	\`secondary_muscles\` text NOT NULL,
	\`equipment\` text,
	\`exercise_type\` text NOT NULL,
	\`instructions\` text,
	\`weight_applicable\` integer NOT NULL,
	\`is_custom\` integer NOT NULL,
	\`deleted_at\` integer,
	\`updated_at\` integer NOT NULL
);`,
  `CREATE INDEX \`exercises_name_idx\` ON \`exercises\` (\`name\`);`,
  `CREATE INDEX \`exercises_primary_muscle_idx\` ON \`exercises\` (\`primary_muscle\`);`,
] as const;
