// Generated by scripts/build-migrations.mjs. Do not edit.
export const name = '0002_fantastic_hellcat';
export const version = 3;
export const statements = [
  `CREATE TABLE \`plan_days\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`plan_version_id\` text NOT NULL,
	\`weekday\` integer NOT NULL,
	\`custom_name\` text,
	\`is_rest_day\` integer NOT NULL,
	FOREIGN KEY (\`plan_version_id\`) REFERENCES \`plan_versions\`(\`id\`) ON UPDATE no action ON DELETE cascade
);`,
  `CREATE INDEX \`plan_days_version_idx\` ON \`plan_days\` (\`plan_version_id\`);`,
  `CREATE UNIQUE INDEX \`plan_days_version_weekday_idx\` ON \`plan_days\` (\`plan_version_id\`,\`weekday\`);`,
  `CREATE TABLE \`plan_versions\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`effective_from\` integer NOT NULL,
	\`effective_to\` integer
);`,
  `CREATE INDEX \`plan_versions_effective_idx\` ON \`plan_versions\` (\`effective_from\`,\`effective_to\`);`,
  `CREATE TABLE \`planned_exercises\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`plan_day_id\` text NOT NULL,
	\`exercise_id\` text NOT NULL,
	\`order_index\` integer NOT NULL,
	FOREIGN KEY (\`plan_day_id\`) REFERENCES \`plan_days\`(\`id\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`exercise_id\`) REFERENCES \`exercises\`(\`id\`) ON UPDATE no action ON DELETE no action
);`,
  `CREATE INDEX \`planned_exercises_day_idx\` ON \`planned_exercises\` (\`plan_day_id\`);`,
  `CREATE TABLE \`planned_sets\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`planned_exercise_id\` text NOT NULL,
	\`set_number\` integer NOT NULL,
	\`target_reps\` integer NOT NULL,
	\`target_weight\` real,
	FOREIGN KEY (\`planned_exercise_id\`) REFERENCES \`planned_exercises\`(\`id\`) ON UPDATE no action ON DELETE cascade
);`,
  `CREATE INDEX \`planned_sets_exercise_idx\` ON \`planned_sets\` (\`planned_exercise_id\`);`,
] as const;
