// Generated by scripts/build-migrations.mjs. Do not edit.
export const name = '0003_prune_plan_orphans';
export const version = 4;
export const statements = [
  `DELETE FROM \`plan_days\` WHERE \`plan_version_id\` NOT IN (SELECT \`id\` FROM \`plan_versions\`);`,
  `DELETE FROM \`planned_exercises\` WHERE \`plan_day_id\` NOT IN (SELECT \`id\` FROM \`plan_days\`);`,
  `DELETE FROM \`planned_sets\` WHERE \`planned_exercise_id\` NOT IN (SELECT \`id\` FROM \`planned_exercises\`);`,
] as const;
