// Generated by scripts/build-migrations.mjs. Do not edit.
export const name = '0004_workout_sessions';
export const version = 5;
export const statements = [
  `CREATE TABLE \`performed_exercises\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workout_session_id\` text NOT NULL,
	\`exercise_id\` text NOT NULL,
	\`planned_exercise_id\` text,
	\`order_index\` integer NOT NULL,
	\`status\` text NOT NULL,
	FOREIGN KEY (\`workout_session_id\`) REFERENCES \`workout_sessions\`(\`id\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`exercise_id\`) REFERENCES \`exercises\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`planned_exercise_id\`) REFERENCES \`planned_exercises\`(\`id\`) ON UPDATE no action ON DELETE set null
);`,
  `CREATE INDEX \`performed_exercises_session_idx\` ON \`performed_exercises\` (\`workout_session_id\`);`,
  `CREATE INDEX \`performed_exercises_exercise_idx\` ON \`performed_exercises\` (\`exercise_id\`);`,
  `CREATE TABLE \`performed_sets\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`performed_exercise_id\` text NOT NULL,
	\`set_number\` integer NOT NULL,
	\`target_reps\` integer,
	\`target_weight\` real,
	\`actual_reps\` integer,
	\`actual_weight\` real,
	\`status\` text NOT NULL,
	\`is_unplanned\` integer NOT NULL,
	\`completed_at\` integer,
	FOREIGN KEY (\`performed_exercise_id\`) REFERENCES \`performed_exercises\`(\`id\`) ON UPDATE no action ON DELETE cascade
);`,
  `CREATE INDEX \`performed_sets_exercise_idx\` ON \`performed_sets\` (\`performed_exercise_id\`);`,
  `CREATE TABLE \`workout_sessions\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`date\` integer NOT NULL,
	\`plan_version_id\` text,
	\`plan_day_id\` text,
	\`day_name_snapshot\` text NOT NULL,
	\`status\` text NOT NULL,
	\`started_at\` integer NOT NULL,
	\`completed_at\` integer,
	FOREIGN KEY (\`plan_version_id\`) REFERENCES \`plan_versions\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`plan_day_id\`) REFERENCES \`plan_days\`(\`id\`) ON UPDATE no action ON DELETE set null
);`,
  `CREATE INDEX \`workout_sessions_date_idx\` ON \`workout_sessions\` (\`date\`);`,
  `CREATE UNIQUE INDEX \`workout_sessions_date_unique\` ON \`workout_sessions\` (\`date\`);`,
] as const;
