// Generated by scripts/build-migrations.mjs. Do not edit.
export const name = '0005_futuristic_malcolm_colcord';
export const version = 6;
export const statements = [
  `ALTER TABLE \`settings\` ADD \`theme_mode\` text DEFAULT 'system' NOT NULL;`,
] as const;
