// Generated by scripts/build-migrations.mjs. Do not edit.
export const name = '0006_neat_demogoblin';
export const version = 7;
export const statements = [
  `ALTER TABLE \`performed_exercises\` ADD \`notes\` text;`,
  `ALTER TABLE \`performed_exercises\` ADD \`substituted_from_exercise_id\` text REFERENCES exercises(id);`,
] as const;
