// Generated by scripts/build-migrations.mjs. Do not edit.
import * as m1 from './0000_unusual_the_spike';
import * as m2 from './0001_safe_darkstar';
import * as m3 from './0002_fantastic_hellcat';
import * as m4 from './0003_prune_plan_orphans';
import * as m5 from './0004_workout_sessions';

export type Migration = {
  readonly version: number;
  readonly name: string;
  readonly statements: readonly string[];
};

export const migrations: readonly Migration[] = [
  m1,
  m2,
  m3,
  m4,
  m5,
];
