// Generated by scripts/build-migrations.mjs. Do not edit.
import * as m1 from './0000_unusual_the_spike';

export type Migration = {
  readonly version: number;
  readonly name: string;
  readonly statements: readonly string[];
};

export const migrations: readonly Migration[] = [
  m1,
];
